---

- become: yes
#  vars_prompt:
#  - name: "pass_nova"
#    promt: "Enter password"                                #password : nova
  tasks:
  - name: create nova user
    user: name=nova password=nova
#  - name: Create openstack role
#    os_user_role:
#      cloud: openstack
#      user: nova
#      role: admin
#      project: project
#      keystone_user:
#      user: nova
#      role: admin
#      password: nova
#  - name: Create nova endpoints
#    keystone_user:
#      endpoint: http://controller:8774/v2.1/%\(tenant_id\)s
#      state: present
#      name: admin

